#!/usr/bin/env python3
"""Cut the film into one clip per voice-over line, so each line can be read against its own
picture instead of against a four-minute file.

WHY THE TIMES COME FROM VO.md. The table in VO.md is generated from the beats the recorder
measured, so it is the only place where the script and the film are known to agree. Hardcoding
the cut points here would create a second list that drifts the moment a beat moves -- which is
exactly what happened to the beat table on 2026-09-09, when moving the boundary diagram left a
script whose rows read 3:05, 3:16, 0:48. This reads VO.md and cannot disagree with it.

Each clip runs from its line's cue to the next line's cue, so what you see is the whole picture
that line plays over, not just the seconds you are speaking. The two plates are included and
named as plates: nothing is read over them, and they are here so the assembly has every frame.

RE-ENCODED, not stream-copied. `-c copy` can only cut on a keyframe, so a copy-split silently
starts each clip up to a second early or late -- fatal when the point of the clip is to show
you where a line lands.

    python3 dashboard/video/split-scenes.py
    python3 dashboard/video/split-scenes.py --out /tmp/scenes
"""
import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
VO = ROOT / "dashboard/video/VO.md"
FILM = ROOT / "dashboard/media/reckn-demo-v3.mp4"
ROW = re.compile(r"^\|\s*(—|\d+)\s*\|\s*(\d+):(\d\d)\s*\|\s*([\d.]+) s\s*\|\s*([^|]*)\|\s*(.*?)\s*\|\s*$")


def slug(text: str) -> str:
    t = re.sub(r"\*|\(|\)|_|`", "", text).strip().strip('"')
    t = re.sub(r"[^A-Za-z0-9 ]", " ", t).lower().split()
    return "-".join(t[:5]) or "plate"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "dashboard/media/scenes"))
    args = ap.parse_args()

    if not FILM.exists():
        sys.exit(f"split-scenes: {FILM} does not exist — record the film first")

    dur = float(subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(FILM)],
        capture_output=True, text=True, check=True).stdout.strip())

    rows = []
    for line in VO.read_text().splitlines():
        m = ROW.match(line)
        if not m or m.group(1) == "#":
            continue
        num, mm, ss, hold, _words, text = m.groups()
        rows.append({"n": num, "at": int(mm) * 60 + int(ss), "hold": float(hold), "text": text})
    if len(rows) < 10:
        sys.exit(f"split-scenes: only {len(rows)} rows parsed out of VO.md — has the table changed shape?")

    # A plate cue with a spoken line arriving a second later is one shot, not two. Cutting on
    # both produced a one-second clip of the closing plate and then the line that plays over
    # it, which is a clip nobody can record against. Fold a row into the next when the next cue
    # is closer than this -- the plate keeps its picture, the line keeps its context.
    MERGE_UNDER = 2.5
    merged = []
    for i, r in enumerate(rows):
        nxt = rows[i + 1]["at"] if i + 1 < len(rows) else None
        if nxt is not None and nxt - r["at"] < MERGE_UNDER and r["n"] == "—":
            rows[i + 1]["at"] = r["at"]          # the next row starts where the plate started
            continue
        merged.append(r)
    rows = merged

    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for f in out.glob("*.mp4"):
        f.unlink()

    manifest = ["| clip | line | in | plays for | you say |", "|---|---|---|---|---|"]
    for i, r in enumerate(rows):
        end = rows[i + 1]["at"] if i + 1 < len(rows) else dur
        length = end - r["at"]
        label = "plate" if r["n"] == "—" else f"line{int(r['n']):02d}"
        name = f"{i:02d}_{r['at']//60}m{r['at']%60:02d}s_{label}_{slug(r['text'])}.mp4"
        subprocess.run(
            ["ffmpeg", "-v", "error", "-ss", str(r["at"]), "-t", f"{length:.3f}", "-i", str(FILM),
             "-c:v", "libx264", "-crf", "24", "-pix_fmt", "yuv420p", "-movflags", "+faststart",
             "-an", str(out / name), "-y"], check=True)
        say = "*(nothing — plate)*" if r["n"] == "—" else r["text"]
        manifest.append(f"| `{name}` | {r['n']} | {r['at']//60}:{r['at']%60:02d} | "
                        f"{length:.1f} s | {say} |")
        print(f"  {name}  {length:.1f}s")

    (out / "README.md").write_text(
        "# Scene clips — one per voice-over line\n\n"
        "Generated by `dashboard/video/split-scenes.py` from `dashboard/video/VO.md` and\n"
        "`dashboard/media/reckn-demo-v3.mp4`. Read each line against its own clip, then assemble\n"
        "the audio against the full film — the clips are for recording, not for submission.\n\n"
        "Every clip runs from its cue to the next cue, so you see the whole picture the line\n"
        "plays over. `plays for` is that window; the budget in VO.md is how long the line itself\n"
        "may run inside it.\n\n" + "\n".join(manifest) + "\n")
    print(f"\n{len(rows)} clips + README.md in {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
